CREATE USER 'repl'@'%'
IDENTIFIED BY 'repl123';
GRANT REPLICATION SLAVE ON *.* TO 'repl'@'%';
FLUSH PRIVILEGES;

CREATE USER 'app'@'%'
IDENTIFIED BY 'app123';
GRANT all PRIVILEGES ON *.* TO 'app'@'%';
FLUSH PRIVILEGES;